openapi: 3.0.1
info:
  title: Company
  version: '1.0'
servers:
  - url: /
security:
  - Bearer: [ ]
tags:
  - name: Company
    description: Handles information about employees
paths:
  /api-docs:
    get:
      tags:
        - Company
      summary: OpenAPI specification
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
      security:
        - default: [ ]
      x-auth-type: None
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/{municipalityId}/{orgId}/companyid':
    get:
      tags:
        - Company
      parameters:
        - name: orgId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginName'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginName'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginName'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - default: [ ]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/{municipalityId}/{companyId}/legalentityid':
    get:
      tags:
        - Company
      parameters:
        - name: companyId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginName'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginName'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LoginName'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - default: [ ]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/{municipalityId}/orgnodesroot':
    get:
      tags:
        - Company
      parameters:
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - default: [ ]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/{municipalityId}/{companyId}/orgnodes':
    get:
      tags:
        - Company
      parameters:
        - name: companyId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
            text/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Organization'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - default: [ ]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
  '/{municipalityId}/{orgId}/orgtree':
    get:
      tags:
        - Company
      parameters:
        - name: orgId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
            format: int32
        - name: municipalityId
          in: path
          description: Kommunkod
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/OrganizationTree'
            application/json:
              schema:
                $ref: '#/components/schemas/OrganizationTree'
            text/json:
              schema:
                $ref: '#/components/schemas/OrganizationTree'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
      security:
        - default: [ ]
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
components:
  schemas:
    LoginName:
      type: object
      properties:
        domain:
          type: string
          nullable: true
        loginName:
          type: string
          nullable: true
      additionalProperties: false
    Organization:
      type: object
      properties:
        orgId:
          type: integer
          format: int32
        orgName:
          type: string
          nullable: true
        parentId:
          type: integer
          format: int32
          nullable: true
        isLeafLevel:
          type: boolean
        treeLevel:
          type: integer
          format: int32
        responsibilityCode:
          type: string
          nullable: true
        responsibilityCodePartList:
          type: string
          nullable: true
        companyId:
          type: integer
          format: int32
        municipalityId:
          type: string
          nullable: true
      additionalProperties: false
    OrganizationTree:
      type: object
      properties:
        orgId:
          type: integer
          format: int32
        treeLevel:
          type: integer
          format: int32
        orgName:
          type: string
          nullable: true
        parentId:
          type: integer
          format: int32
        isLeafLevel:
          type: boolean
        companyId:
          type: integer
          format: int32
        responsibilityCode:
          type: string
          nullable: true
        responsibilityList:
          type: string
          nullable: true
        organizations:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/OrganizationTree'
      additionalProperties: false
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
  securitySchemes:
    Bearer:
      type: apiKey
      description: JWT Authorization header using the Bearer scheme.
      name: X-JWT-Assertion
      in: header
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'https://test.com'
          scopes: { }
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - Internal-Key
    - testKey
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
  empty: false
x-wso2-production-endpoints:
  urls:
    - 'http://masterdataapi-test.sundsvall.se/api/v1/company'
  type: http
x-wso2-basePath: /company/1.0
x-wso2-transports:
  - http
  - https
x-wso2-application-security:
  security-types:
    - oauth2
  optional: false
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
